/**
 * Landing Page Component
 * First page of the Primary Cell Assessment - introduces cellular pain science
 * and qualifies users based on chronic pain duration
 */

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAssessment } from '@context/AssessmentContext';
import { Button } from '@components/common/Button';
import styles from './LandingPage.module.css';

/**
 * Educational content block interface
 */
interface ContentBlock {
  id: number;
  title: string;
  description: string;
  icon: string;
}

/**
 * Landing Page Component
 *
 * @description Entry point for the assessment flow. Educates users about cellular
 * pain science and routes based on chronic pain duration (6+ months qualification).
 *
 * Features:
 * - Hero section with compelling headline
 * - Educational content blocks explaining damage types
 * - Visual section with AI-generated image descriptions
 * - Yes/No button routing logic
 * - Framer Motion entrance animations
 * - Mobile-first responsive design
 * - WCAG 2.1 AA accessibility
 *
 * @returns {JSX.Element} Landing page component
 */
const LandingPage: React.FC = () => {
  const navigate = useNavigate();
  const { updateResponse } = useAssessment();
  const [selectedAnswer, setSelectedAnswer] = useState<boolean | null>(null);

  /**
   * Educational content blocks data
   */
  const contentBlocks: ContentBlock[] = [
    {
      id: 1,
      title: 'Tissue & Bone Damage',
      description: 'Structural damage to your body\'s physical framework. When bones break or tissues tear, your cells remember these injuries at the molecular level.',
      icon: '🦴',
    },
    {
      id: 2,
      title: 'New Cellular Damage',
      description: 'Current pain signals generated by recent cellular injury. Your Primary Cells are actively responding to ongoing damage and inflammation.',
      icon: '⚡',
    },
    {
      id: 3,
      title: 'Prenatal Cellular Damage',
      description: 'Ancient pain patterns encoded before birth. Research shows that trauma experienced during development can leave lasting cellular imprints.',
      icon: '🧬',
    },
  ];

  /**
   * Handles answer selection and navigation
   *
   * @param hasChronicPain - Whether user has chronic pain for 6+ months
   */
  const handleAnswer = (hasChronicPain: boolean): void => {
    setSelectedAnswer(hasChronicPain);

    updateResponse({
      painDuration: hasChronicPain ? 12 : 3,
    });

    setTimeout(() => {
      if (hasChronicPain) {
        navigate('/cellular-science');
      } else {
        navigate('/waiting-list');
      }
    }, 400);
  };

  /**
   * Container animation variants
   */
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  };

  /**
   * Item animation variants
   */
  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
        ease: 'easeOut',
      },
    },
  };

  /**
   * Button animation variants
   */
  const buttonVariants = {
    hidden: { opacity: 0, scale: 0.9 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.4,
        ease: 'easeOut',
      },
    },
    hover: {
      scale: 1.05,
      transition: {
        duration: 0.2,
      },
    },
    tap: {
      scale: 0.95,
    },
  };

  /**
   * Save progress to localStorage on mount
   */
  useEffect(() => {
    try {
      localStorage.setItem('assessment_last_page', '/');
      localStorage.setItem('assessment_timestamp', new Date().toISOString());
    } catch (error) {
      // Silently fail if localStorage is not available
    }
  }, []);

  return (
    <motion.div
      className={styles.landing}
      initial="hidden"
      animate="visible"
      variants={containerVariants}
    >
      {/* Hero Section */}
      <motion.section
        className={styles.landing__hero}
        variants={itemVariants}
        role="banner"
      >
        <h1 className={styles.landing__headline}>
          Scientists Just Proved Chronic Pain Lives Inside Your Cells—And We Can Now Fix It
        </h1>

        <p className={styles.landing__subheadline}>
          For decades, medicine treated pain as a symptom to manage. New research reveals
          the truth: chronic pain is stored in your Primary Cells as damaged RNA patterns.
          Instead of masking pain, we repair the cells that generate it.
        </p>
      </motion.section>

      {/* Visual Section */}
      <motion.section
        className={styles.landing__visual}
        variants={itemVariants}
        aria-label="Cellular science visualization"
      >
        <div className={styles.landing__imageContainer}>
          <div className={styles.landing__imagePlaceholder} role="img" aria-label="Microscopic view of Primary Cells with highlighted RNA patterns showing pain storage at the cellular level">
            <span className={styles.landing__imageText}>
              Primary Cell RNA Pattern Analysis
            </span>
            <p className={styles.landing__imageCaption}>
              AI visualization: RNA molecules storing pain signals in Primary Cells
            </p>
          </div>
        </div>
      </motion.section>

      {/* Educational Content Blocks */}
      <motion.section
        className={styles.landing__education}
        variants={itemVariants}
        aria-labelledby="damage-types-heading"
      >
        <h2 id="damage-types-heading" className={styles.landing__sectionTitle}>
          Understanding Three Types of Cellular Damage
        </h2>

        <div className={styles.landing__contentGrid}>
          {contentBlocks.map((block, index) => (
            <motion.article
              key={block.id}
              className={styles.landing__contentBlock}
              variants={{
                hidden: { opacity: 0, y: 20 },
                visible: {
                  opacity: 1,
                  y: 0,
                  transition: {
                    duration: 0.5,
                    delay: index * 0.15,
                    ease: 'easeOut',
                  },
                },
              }}
            >
              <div className={styles.landing__blockIcon} aria-hidden="true">
                {block.icon}
              </div>
              <h3 className={styles.landing__blockTitle}>{block.title}</h3>
              <p className={styles.landing__blockDescription}>{block.description}</p>
            </motion.article>
          ))}
        </div>
      </motion.section>

      {/* Qualification Question */}
      <motion.section
        className={styles.landing__qualification}
        variants={itemVariants}
        aria-labelledby="qualification-question"
      >
        <h2 id="qualification-question" className={styles.landing__question}>
          Have you had chronic pain for 6+ months?
        </h2>

        <p className={styles.landing__questionHelper}>
          This helps us determine if cellular repair therapy is right for you.
        </p>

        <div className={styles.landing__buttonGroup} role="group" aria-label="Chronic pain duration selection">
          <motion.div
            variants={buttonVariants}
            whileHover="hover"
            whileTap="tap"
          >
            <Button
              variant="primary"
              size="large"
              onClick={() => handleAnswer(true)}
              aria-label="Yes, I have had chronic pain for 6 or more months"
              className={`${styles.landing__button} ${
                selectedAnswer === true ? styles['landing__button--selected'] : ''
              }`}
            >
              <span className={styles.landing__buttonIcon}>✓</span>
              Yes
            </Button>
          </motion.div>

          <motion.div
            variants={buttonVariants}
            whileHover="hover"
            whileTap="tap"
          >
            <Button
              variant="secondary"
              size="large"
              onClick={() => handleAnswer(false)}
              aria-label="No, I have not had chronic pain for 6 or more months"
              className={`${styles.landing__button} ${
                selectedAnswer === false ? styles['landing__button--selected'] : ''
              }`}
            >
              <span className={styles.landing__buttonIcon}>✗</span>
              No
            </Button>
          </motion.div>
        </div>
      </motion.section>

      {/* Trust Indicators */}
      <motion.aside
        className={styles.landing__trust}
        variants={itemVariants}
        aria-label="Research credibility indicators"
      >
        <p className={styles.landing__trustText}>
          Based on peer-reviewed research from Johns Hopkins, MIT, and Stanford University
        </p>
      </motion.aside>
    </motion.div>
  );
};

export default LandingPage;
