export interface HeroVisual {
  id: string;
  lead: string;
  support?: string;
  illustration: {
    key: string;
    alt: string;
    caption: string;
  };
}

export const HERO_VISUALS: HeroVisual[] = [
  {
    id: 'tissue-bone',
    lead: 'Tissue & Bone Damage',
    support: "Structural damage to your body's physical framework. Doctors treat this—it heals in 6 months.",
    illustration: {
      key: 'tissue-bone',
      alt: 'Bone and tissue damage with no cellular overlays.',
      // Proposed caption: placeholder description until final artwork is ready
      caption: 'Bone and muscle tear before cellular damage begins.',
    },
  },
  {
    id: 'new-cellular',
    lead: 'New Cellular Damage',
    support: "Current pain signals generated by recent cellular injury. Doctors don’t treat this—it doesn’t heal on its own.",
    illustration: {
      key: 'new-cellular',
      alt: 'Injury with pulsing dots representing new cellular damage.',
      caption: 'Same injury with new cellular damage pulsing at the site.',
    },
  },
  {
    id: 'prenatal-cellular',
    lead: 'Prenatal Cellular Damage',
    support: 'Current pain signals triggered by past injuries from before and during your fetal development. Doctors don’t even know this exists.',
    illustration: {
      key: 'prenatal-cellular',
      alt: 'Prenatal cellular damage dots layered beyond the injury site.',
      caption: 'Prenatal cellular damage dots activating around the injury.',
    },
  },
  {
    id: 'persistent-cellular',
    lead: 'After 6 months, your bone & tissue damage is healed, but your cellular damage persists, keeping your chronic pain in place today.',
    illustration: {
      key: 'persistent-cellular',
      alt: 'Healed bone and tissue with cellular damage dots still active.',
      caption: 'Healed structure with persistent cellular damage signals.',
    },
  },
];
